### ISSUE TITLE
小数点以下の桁数を変えられる機能

### ISSUE THREAD

**Issue by Reputeless** [voidproc/siv3d-palette-browser#1]
`ColorF{ 0.8, 0.9, 1.0 }` のように文字数が少ない色を得られる機能があると、
Siv3D のサンプルコード作成時に気軽に使えて非常に助かります。

**Comment by voidproc** [comment]
試しに、e4f84c4 で機能追加をしてみました。
"Control..." の中にある "Precision" に桁数を入力するかたちです。

**Comment by Reputeless** [comment]
求めていたもので、完璧です。ありがとうございます！

**Comment by voidproc** [comment]
このあとは ColorF モードでのみ、小数点以下の桁数に応じて実際の（桁落ちした）色で
表示されるようにしようかと思っています。
